spring:

  logging:
    level:
      root: INFO

      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

  datasource:
    url: jdbc:h2:mem:jonasingvar
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2

  h2:
    console:
      enabled: true   # web console http://localhost/h2-console
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false